# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTGraphicInterfaces/MasterMainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbr_load_image = QtWidgets.QGroupBox(self.centralwidget)
        self.gbr_load_image.setGeometry(QtCore.QRect(10, 10, 831, 71))
        self.gbr_load_image.setObjectName("gbr_load_image")
        self.btn_load_image = QtWidgets.QPushButton(self.gbr_load_image)
        self.btn_load_image.setGeometry(QtCore.QRect(10, 30, 151, 23))
        self.btn_load_image.setObjectName("btn_load_image")
        self.lbl_load_image = QtWidgets.QLabel(self.gbr_load_image)
        self.lbl_load_image.setGeometry(QtCore.QRect(170, 30, 601, 21))
        self.lbl_load_image.setObjectName("lbl_load_image")
        self.scrollArea_filters = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_filters.setGeometry(QtCore.QRect(10, 200, 831, 201))
        self.scrollArea_filters.setWidgetResizable(True)
        self.scrollArea_filters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_filters.setObjectName("scrollArea_filters")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 829, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.dz_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.dz_frame.setMinimumSize(QtCore.QSize(400, 80))
        self.dz_frame.setMaximumSize(QtCore.QSize(400, 100))
        self.dz_frame.setStyleSheet("")
        self.dz_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dz_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dz_frame.setObjectName("dz_frame")
        self.dz_grb_draw_zones = QtWidgets.QGroupBox(self.dz_frame)
        self.dz_grb_draw_zones.setGeometry(QtCore.QRect(0, 0, 391, 101))
        self.dz_grb_draw_zones.setObjectName("dz_grb_draw_zones")
        self.dz_btn_draw_zone = QtWidgets.QPushButton(self.dz_grb_draw_zones)
        self.dz_btn_draw_zone.setGeometry(QtCore.QRect(30, 20, 91, 23))
        self.dz_btn_draw_zone.setObjectName("dz_btn_draw_zone")
        self.dz__lbl_draw_zone = QtWidgets.QLabel(self.dz_grb_draw_zones)
        self.dz__lbl_draw_zone.setGeometry(QtCore.QRect(10, 20, 16, 21))
        self.dz__lbl_draw_zone.setAutoFillBackground(False)
        self.dz__lbl_draw_zone.setStyleSheet("background: rgb(0, 255, 0);\n"
"border: 1px solid black;")
        self.dz__lbl_draw_zone.setText("")
        self.dz__lbl_draw_zone.setObjectName("dz__lbl_draw_zone")
        self.dz_btn_clean = QtWidgets.QPushButton(self.dz_grb_draw_zones)
        self.dz_btn_clean.setGeometry(QtCore.QRect(30, 50, 91, 23))
        self.dz_btn_clean.setObjectName("dz_btn_clean")
        self.dz_btn_view_zone = QtWidgets.QPushButton(self.dz_grb_draw_zones)
        self.dz_btn_view_zone.setGeometry(QtCore.QRect(150, 20, 81, 23))
        self.dz_btn_view_zone.setObjectName("dz_btn_view_zone")
        self.dz_btn_delete = QtWidgets.QPushButton(self.dz_grb_draw_zones)
        self.dz_btn_delete.setGeometry(QtCore.QRect(150, 50, 81, 23))
        self.dz_btn_delete.setObjectName("dz_btn_delete")
        self.dz_cbx_executed = QtWidgets.QCheckBox(self.dz_grb_draw_zones)
        self.dz_cbx_executed.setGeometry(QtCore.QRect(310, 10, 70, 17))
        self.dz_cbx_executed.setObjectName("dz_cbx_executed")
        self.gridLayout.addWidget(self.dz_frame, 0, 0, 1, 1)
        self.sfz_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.sfz_frame.setMinimumSize(QtCore.QSize(400, 80))
        self.sfz_frame.setMaximumSize(QtCore.QSize(400, 100))
        self.sfz_frame.setStyleSheet("")
        self.sfz_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sfz_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sfz_frame.setObjectName("sfz_frame")
        self.ls_grb_lines = QtWidgets.QGroupBox(self.sfz_frame)
        self.ls_grb_lines.setGeometry(QtCore.QRect(0, 0, 391, 100))
        self.ls_grb_lines.setObjectName("ls_grb_lines")
        self.ls_lbl_line_color = QtWidgets.QLabel(self.ls_grb_lines)
        self.ls_lbl_line_color.setGeometry(QtCore.QRect(10, 30, 16, 21))
        self.ls_lbl_line_color.setAutoFillBackground(False)
        self.ls_lbl_line_color.setStyleSheet("background: rgb(255, 255, 255 );\n"
"border: 1px solid black;")
        self.ls_lbl_line_color.setText("")
        self.ls_lbl_line_color.setObjectName("ls_lbl_line_color")
        self.ls_btn_capture_color = QtWidgets.QPushButton(self.ls_grb_lines)
        self.ls_btn_capture_color.setGeometry(QtCore.QRect(30, 30, 71, 23))
        self.ls_btn_capture_color.setObjectName("ls_btn_capture_color")
        self.ls_btn_apply_color = QtWidgets.QPushButton(self.ls_grb_lines)
        self.ls_btn_apply_color.setGeometry(QtCore.QRect(30, 60, 71, 23))
        self.ls_btn_apply_color.setObjectName("ls_btn_apply_color")
        self.ls_sld_line_tolerance = QtWidgets.QSlider(self.ls_grb_lines)
        self.ls_sld_line_tolerance.setGeometry(QtCore.QRect(110, 30, 161, 22))
        self.ls_sld_line_tolerance.setMinimum(5)
        self.ls_sld_line_tolerance.setMaximum(30)
        self.ls_sld_line_tolerance.setPageStep(1)
        self.ls_sld_line_tolerance.setSliderPosition(11)
        self.ls_sld_line_tolerance.setTracking(False)
        self.ls_sld_line_tolerance.setOrientation(QtCore.Qt.Horizontal)
        self.ls_sld_line_tolerance.setObjectName("ls_sld_line_tolerance")
        self.ls_lbl_line_tolerance = QtWidgets.QLabel(self.ls_grb_lines)
        self.ls_lbl_line_tolerance.setGeometry(QtCore.QRect(180, 60, 31, 16))
        self.ls_lbl_line_tolerance.setObjectName("ls_lbl_line_tolerance")
        self.ls_btn_delete = QtWidgets.QPushButton(self.ls_grb_lines)
        self.ls_btn_delete.setGeometry(QtCore.QRect(280, 30, 61, 23))
        self.ls_btn_delete.setObjectName("ls_btn_delete")
        self.gridLayout.addWidget(self.sfz_frame, 0, 1, 1, 1)
        self.scrollArea_filters.setWidget(self.scrollAreaWidgetContents)
        self.gbr_add_filter = QtWidgets.QGroupBox(self.centralwidget)
        self.gbr_add_filter.setGeometry(QtCore.QRect(10, 90, 831, 71))
        self.gbr_add_filter.setCheckable(False)
        self.gbr_add_filter.setObjectName("gbr_add_filter")
        self.btn_draw_zones = QtWidgets.QPushButton(self.gbr_add_filter)
        self.btn_draw_zones.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.btn_draw_zones.setObjectName("btn_draw_zones")
        self.btn_color_lines = QtWidgets.QPushButton(self.gbr_add_filter)
        self.btn_color_lines.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.btn_color_lines.setObjectName("btn_color_lines")
        self.lbl_filters = QtWidgets.QLabel(self.centralwidget)
        self.lbl_filters.setGeometry(QtCore.QRect(400, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_filters.setFont(font)
        self.lbl_filters.setObjectName("lbl_filters")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbr_load_image.setTitle(_translate("MainWindow", "Carga de imagen"))
        self.btn_load_image.setText(_translate("MainWindow", "Cargar imagen"))
        self.lbl_load_image.setText(_translate("MainWindow", "..."))
        self.dz_grb_draw_zones.setTitle(_translate("MainWindow", "Dibujar zonas"))
        self.dz_btn_draw_zone.setText(_translate("MainWindow", "Dibujar"))
        self.dz_btn_clean.setText(_translate("MainWindow", "Limpiar"))
        self.dz_btn_view_zone.setText(_translate("MainWindow", "Ver"))
        self.dz_btn_delete.setText(_translate("MainWindow", "Eliminar"))
        self.dz_cbx_executed.setText(_translate("MainWindow", "Ejecutado"))
        self.ls_grb_lines.setTitle(_translate("MainWindow", "Selección de color lineas"))
        self.ls_btn_capture_color.setText(_translate("MainWindow", "Capturar"))
        self.ls_btn_apply_color.setText(_translate("MainWindow", "Aplicar"))
        self.ls_lbl_line_tolerance.setText(_translate("MainWindow", "11 %"))
        self.ls_btn_delete.setText(_translate("MainWindow", "Eliminar"))
        self.gbr_add_filter.setTitle(_translate("MainWindow", "Agregar filtros"))
        self.btn_draw_zones.setText(_translate("MainWindow", "Dibujar zonas"))
        self.btn_color_lines.setText(_translate("MainWindow", "Color lineas"))
        self.lbl_filters.setText(_translate("MainWindow", "Filtros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
