# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTGraphicInterfaces/MasterMainInterface.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 646)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbr_load_image = QtWidgets.QGroupBox(self.centralwidget)
        self.gbr_load_image.setGeometry(QtCore.QRect(10, 10, 831, 71))
        self.gbr_load_image.setObjectName("gbr_load_image")
        self.btn_load_image = QtWidgets.QPushButton(self.gbr_load_image)
        self.btn_load_image.setGeometry(QtCore.QRect(10, 30, 151, 23))
        self.btn_load_image.setObjectName("btn_load_image")
        self.lbl_load_image = QtWidgets.QLabel(self.gbr_load_image)
        self.lbl_load_image.setGeometry(QtCore.QRect(170, 30, 601, 21))
        self.lbl_load_image.setObjectName("lbl_load_image")
        self.scrollArea_filters = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_filters.setGeometry(QtCore.QRect(10, 200, 881, 401))
        self.scrollArea_filters.setMinimumSize(QtCore.QSize(400, 200))
        self.scrollArea_filters.setWidgetResizable(True)
        self.scrollArea_filters.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_filters.setObjectName("scrollArea_filters")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 879, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.sfz_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.sfz_frame.setMinimumSize(QtCore.QSize(400, 80))
        self.sfz_frame.setMaximumSize(QtCore.QSize(400, 100))
        self.sfz_frame.setStyleSheet("")
        self.sfz_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sfz_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sfz_frame.setObjectName("sfz_frame")
        self.ls_grb_lines = QtWidgets.QGroupBox(self.sfz_frame)
        self.ls_grb_lines.setGeometry(QtCore.QRect(0, 0, 391, 100))
        self.ls_grb_lines.setObjectName("ls_grb_lines")
        self.ls_lbl_line_color = QtWidgets.QLabel(self.ls_grb_lines)
        self.ls_lbl_line_color.setGeometry(QtCore.QRect(10, 30, 16, 21))
        self.ls_lbl_line_color.setAutoFillBackground(False)
        self.ls_lbl_line_color.setStyleSheet("background: rgb(255, 255, 255 );\n"
"border: 1px solid black;")
        self.ls_lbl_line_color.setText("")
        self.ls_lbl_line_color.setObjectName("ls_lbl_line_color")
        self.ls_btn_capture_color = QtWidgets.QPushButton(self.ls_grb_lines)
        self.ls_btn_capture_color.setGeometry(QtCore.QRect(30, 30, 71, 23))
        self.ls_btn_capture_color.setObjectName("ls_btn_capture_color")
        self.ls_btn_apply_color = QtWidgets.QPushButton(self.ls_grb_lines)
        self.ls_btn_apply_color.setGeometry(QtCore.QRect(30, 60, 71, 23))
        self.ls_btn_apply_color.setObjectName("ls_btn_apply_color")
        self.ls_sld_line_tolerance = QtWidgets.QSlider(self.ls_grb_lines)
        self.ls_sld_line_tolerance.setGeometry(QtCore.QRect(110, 30, 161, 22))
        self.ls_sld_line_tolerance.setMinimum(5)
        self.ls_sld_line_tolerance.setMaximum(30)
        self.ls_sld_line_tolerance.setPageStep(1)
        self.ls_sld_line_tolerance.setSliderPosition(11)
        self.ls_sld_line_tolerance.setTracking(False)
        self.ls_sld_line_tolerance.setOrientation(QtCore.Qt.Horizontal)
        self.ls_sld_line_tolerance.setObjectName("ls_sld_line_tolerance")
        self.ls_lbl_line_tolerance = QtWidgets.QLabel(self.ls_grb_lines)
        self.ls_lbl_line_tolerance.setGeometry(QtCore.QRect(180, 60, 31, 16))
        self.ls_lbl_line_tolerance.setObjectName("ls_lbl_line_tolerance")
        self.ls_btn_delete = QtWidgets.QPushButton(self.ls_grb_lines)
        self.ls_btn_delete.setGeometry(QtCore.QRect(280, 30, 61, 23))
        self.ls_btn_delete.setObjectName("ls_btn_delete")
        self.gridLayout.addWidget(self.sfz_frame, 0, 1, 1, 1)
        self.da_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.da_frame.setMinimumSize(QtCore.QSize(400, 80))
        self.da_frame.setMaximumSize(QtCore.QSize(400, 100))
        self.da_frame.setStyleSheet("")
        self.da_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.da_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.da_frame.setObjectName("da_frame")
        self.da_grb_draw_zones = QtWidgets.QGroupBox(self.da_frame)
        self.da_grb_draw_zones.setGeometry(QtCore.QRect(0, 0, 391, 101))
        self.da_grb_draw_zones.setObjectName("da_grb_draw_zones")
        self.da_lbl_color = QtWidgets.QLabel(self.da_grb_draw_zones)
        self.da_lbl_color.setGeometry(QtCore.QRect(170, 30, 40, 40))
        self.da_lbl_color.setMinimumSize(QtCore.QSize(40, 40))
        self.da_lbl_color.setMaximumSize(QtCore.QSize(40, 40))
        self.da_lbl_color.setAutoFillBackground(False)
        self.da_lbl_color.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid gray;")
        self.da_lbl_color.setText("")
        self.da_lbl_color.setObjectName("da_lbl_color")
        self.da_btn_clean = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_clean.setGeometry(QtCore.QRect(300, 30, 40, 40))
        self.da_btn_clean.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_clean.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_clean.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Desktop/icons/limpiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_clean.setIcon(icon)
        self.da_btn_clean.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_clean.setObjectName("da_btn_clean")
        self.da_btn_delete = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_delete.setGeometry(QtCore.QRect(340, 30, 40, 40))
        self.da_btn_delete.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_delete.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Desktop/icons/eliminar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_delete.setIcon(icon1)
        self.da_btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_delete.setObjectName("da_btn_delete")
        self.da_cbx_executed = QtWidgets.QCheckBox(self.da_grb_draw_zones)
        self.da_cbx_executed.setGeometry(QtCore.QRect(260, 80, 70, 17))
        self.da_cbx_executed.setObjectName("da_cbx_executed")
        self.da_btn_coordinates = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_coordinates.setGeometry(QtCore.QRect(50, 30, 40, 40))
        self.da_btn_coordinates.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_coordinates.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_coordinates.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.da_btn_coordinates.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Desktop/icons/coordenadas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_coordinates.setIcon(icon2)
        self.da_btn_coordinates.setIconSize(QtCore.QSize(36, 36))
        self.da_btn_coordinates.setObjectName("da_btn_coordinates")
        self.da_btn_lines = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_lines.setGeometry(QtCore.QRect(10, 30, 40, 40))
        self.da_btn_lines.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_lines.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_lines.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.da_btn_lines.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Desktop/icons/lineas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_lines.setIcon(icon3)
        self.da_btn_lines.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_lines.setObjectName("da_btn_lines")
        self.da_btn_eraser = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_eraser.setGeometry(QtCore.QRect(90, 30, 40, 40))
        self.da_btn_eraser.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_eraser.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_eraser.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.da_btn_eraser.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../Desktop/icons/borrador.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_eraser.setIcon(icon4)
        self.da_btn_eraser.setIconSize(QtCore.QSize(36, 36))
        self.da_btn_eraser.setObjectName("da_btn_eraser")
        self.da_btn_color = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_color.setGeometry(QtCore.QRect(130, 30, 40, 40))
        self.da_btn_color.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_color.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_color.setStyleSheet("border-color: rgb(255, 85, 0);")
        self.da_btn_color.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../Desktop/icons/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_color.setIcon(icon5)
        self.da_btn_color.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_color.setObjectName("da_btn_color")
        self.da_btn_view = QtWidgets.QPushButton(self.da_grb_draw_zones)
        self.da_btn_view.setGeometry(QtCore.QRect(260, 30, 40, 40))
        self.da_btn_view.setMinimumSize(QtCore.QSize(40, 40))
        self.da_btn_view.setMaximumSize(QtCore.QSize(40, 40))
        self.da_btn_view.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../Desktop/icons/ver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.da_btn_view.setIcon(icon6)
        self.da_btn_view.setIconSize(QtCore.QSize(32, 32))
        self.da_btn_view.setObjectName("da_btn_view")
        self.gridLayout.addWidget(self.da_frame, 0, 0, 1, 1)
        self.cs_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.cs_frame.setMinimumSize(QtCore.QSize(400, 80))
        self.cs_frame.setMaximumSize(QtCore.QSize(400, 100))
        self.cs_frame.setStyleSheet("")
        self.cs_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cs_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cs_frame.setObjectName("cs_frame")
        self.cs_grb_color_space = QtWidgets.QGroupBox(self.cs_frame)
        self.cs_grb_color_space.setGeometry(QtCore.QRect(0, 0, 391, 101))
        self.cs_grb_color_space.setObjectName("cs_grb_color_space")
        self.cs_cbx_color_space = QtWidgets.QComboBox(self.cs_grb_color_space)
        self.cs_cbx_color_space.setGeometry(QtCore.QRect(30, 40, 171, 22))
        self.cs_cbx_color_space.setObjectName("cs_cbx_color_space")
        self.cs_cbx_color_space.addItem("")
        self.cs_apply = QtWidgets.QPushButton(self.cs_grb_color_space)
        self.cs_apply.setGeometry(QtCore.QRect(210, 40, 71, 23))
        self.cs_apply.setObjectName("cs_apply")
        self.cs_view = QtWidgets.QPushButton(self.cs_grb_color_space)
        self.cs_view.setGeometry(QtCore.QRect(290, 40, 71, 23))
        self.cs_view.setObjectName("cs_view")
        self.gridLayout.addWidget(self.cs_frame, 1, 0, 1, 1)
        self.bn_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.bn_frame.setMinimumSize(QtCore.QSize(400, 250))
        self.bn_frame.setStyleSheet("")
        self.bn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bn_frame.setObjectName("bn_frame")
        self.bn_grb_binarize = QtWidgets.QGroupBox(self.bn_frame)
        self.bn_grb_binarize.setGeometry(QtCore.QRect(0, 0, 391, 241))
        self.bn_grb_binarize.setObjectName("bn_grb_binarize")
        self.bn_cbx_s_technique = QtWidgets.QComboBox(self.bn_grb_binarize)
        self.bn_cbx_s_technique.setGeometry(QtCore.QRect(100, 20, 131, 22))
        self.bn_cbx_s_technique.setObjectName("bn_cbx_s_technique")
        self.bn_cbx_s_technique.addItem("")
        self.bn_cbx_s_technique.addItem("")
        self.bn_cbx_s_technique.addItem("")
        self.bn_cbx_s_technique.addItem("")
        self.bn_cbx_s_technique.addItem("")
        self.bn_lbl_s_threshold_simple = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_s_threshold_simple.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.bn_lbl_s_threshold_simple.setObjectName("bn_lbl_s_threshold_simple")
        self.label_2 = QtWidgets.QLabel(self.bn_grb_binarize)
        self.label_2.setGeometry(QtCore.QRect(150, 80, 101, 16))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background:rgb(240, 240, 240)\n"
"")
        self.label_2.setObjectName("label_2")
        self.bn_cbx_ad_method = QtWidgets.QComboBox(self.bn_grb_binarize)
        self.bn_cbx_ad_method.setGeometry(QtCore.QRect(10, 120, 181, 22))
        self.bn_cbx_ad_method.setObjectName("bn_cbx_ad_method")
        self.bn_cbx_ad_method.addItem("")
        self.bn_cbx_ad_method.addItem("")
        self.bn_cbx_ad_type = QtWidgets.QComboBox(self.bn_grb_binarize)
        self.bn_cbx_ad_type.setGeometry(QtCore.QRect(200, 120, 181, 22))
        self.bn_cbx_ad_type.setObjectName("bn_cbx_ad_type")
        self.bn_cbx_ad_type.addItem("")
        self.bn_cbx_ad_type.addItem("")
        self.bn_sld_s_threshold_value = QtWidgets.QSlider(self.bn_grb_binarize)
        self.bn_sld_s_threshold_value.setGeometry(QtCore.QRect(240, 20, 91, 22))
        self.bn_sld_s_threshold_value.setOrientation(QtCore.Qt.Horizontal)
        self.bn_sld_s_threshold_value.setObjectName("bn_sld_s_threshold_value")
        self.bn_lbl_s_threshold_value = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_s_threshold_value.setGeometry(QtCore.QRect(350, 20, 31, 16))
        self.bn_lbl_s_threshold_value.setObjectName("bn_lbl_s_threshold_value")
        self.line = QtWidgets.QFrame(self.bn_grb_binarize)
        self.line.setGeometry(QtCore.QRect(10, 80, 381, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.bn_cbx_ad_block_size_value = QtWidgets.QSlider(self.bn_grb_binarize)
        self.bn_cbx_ad_block_size_value.setGeometry(QtCore.QRect(200, 180, 171, 22))
        self.bn_cbx_ad_block_size_value.setOrientation(QtCore.Qt.Horizontal)
        self.bn_cbx_ad_block_size_value.setObjectName("bn_cbx_ad_block_size_value")
        self.bn_lbl_ad_block_size = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_ad_block_size.setGeometry(QtCore.QRect(200, 160, 47, 13))
        self.bn_lbl_ad_block_size.setObjectName("bn_lbl_ad_block_size")
        self.bn_lbl_ad_block_size_value = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_ad_block_size_value.setGeometry(QtCore.QRect(250, 150, 31, 31))
        self.bn_lbl_ad_block_size_value.setObjectName("bn_lbl_ad_block_size_value")
        self.bn_cbx_ad_constant_value = QtWidgets.QSlider(self.bn_grb_binarize)
        self.bn_cbx_ad_constant_value.setGeometry(QtCore.QRect(10, 180, 171, 22))
        self.bn_cbx_ad_constant_value.setOrientation(QtCore.Qt.Horizontal)
        self.bn_cbx_ad_constant_value.setObjectName("bn_cbx_ad_constant_value")
        self.bn_lbl_ad_constant = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_ad_constant.setGeometry(QtCore.QRect(10, 160, 47, 13))
        self.bn_lbl_ad_constant.setObjectName("bn_lbl_ad_constant")
        self.bn_lbl_ad_constant_value = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_ad_constant_value.setGeometry(QtCore.QRect(60, 150, 31, 31))
        self.bn_lbl_ad_constant_value.setObjectName("bn_lbl_ad_constant_value")
        self.bn_lbl_ad_method = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_ad_method.setGeometry(QtCore.QRect(10, 100, 101, 16))
        self.bn_lbl_ad_method.setObjectName("bn_lbl_ad_method")
        self.bn_lbl_ad_type = QtWidgets.QLabel(self.bn_grb_binarize)
        self.bn_lbl_ad_type.setGeometry(QtCore.QRect(200, 100, 81, 16))
        self.bn_lbl_ad_type.setObjectName("bn_lbl_ad_type")
        self.bn_btn_s_apply = QtWidgets.QPushButton(self.bn_grb_binarize)
        self.bn_btn_s_apply.setGeometry(QtCore.QRect(230, 50, 75, 23))
        self.bn_btn_s_apply.setObjectName("bn_btn_s_apply")
        self.bn_btn_s_view = QtWidgets.QPushButton(self.bn_grb_binarize)
        self.bn_btn_s_view.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.bn_btn_s_view.setObjectName("bn_btn_s_view")
        self.bn_btn_add_view = QtWidgets.QPushButton(self.bn_grb_binarize)
        self.bn_btn_add_view.setGeometry(QtCore.QRect(310, 210, 75, 23))
        self.bn_btn_add_view.setObjectName("bn_btn_add_view")
        self.bn_btn_ad_apply = QtWidgets.QPushButton(self.bn_grb_binarize)
        self.bn_btn_ad_apply.setGeometry(QtCore.QRect(230, 210, 75, 23))
        self.bn_btn_ad_apply.setObjectName("bn_btn_ad_apply")
        self.bn_cbx_s_technique.raise_()
        self.bn_lbl_s_threshold_simple.raise_()
        self.bn_cbx_ad_method.raise_()
        self.bn_cbx_ad_type.raise_()
        self.bn_sld_s_threshold_value.raise_()
        self.bn_lbl_s_threshold_value.raise_()
        self.line.raise_()
        self.bn_cbx_ad_block_size_value.raise_()
        self.bn_lbl_ad_block_size.raise_()
        self.bn_lbl_ad_block_size_value.raise_()
        self.bn_cbx_ad_constant_value.raise_()
        self.bn_lbl_ad_constant.raise_()
        self.bn_lbl_ad_constant_value.raise_()
        self.bn_lbl_ad_method.raise_()
        self.bn_lbl_ad_type.raise_()
        self.label_2.raise_()
        self.bn_btn_s_apply.raise_()
        self.bn_btn_s_view.raise_()
        self.bn_btn_add_view.raise_()
        self.bn_btn_ad_apply.raise_()
        self.gridLayout.addWidget(self.bn_frame, 1, 1, 1, 1)
        self.scrollArea_filters.setWidget(self.scrollAreaWidgetContents)
        self.gbr_add_filter = QtWidgets.QGroupBox(self.centralwidget)
        self.gbr_add_filter.setGeometry(QtCore.QRect(10, 90, 831, 71))
        self.gbr_add_filter.setCheckable(False)
        self.gbr_add_filter.setObjectName("gbr_add_filter")
        self.btn_draw_zones = QtWidgets.QPushButton(self.gbr_add_filter)
        self.btn_draw_zones.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.btn_draw_zones.setObjectName("btn_draw_zones")
        self.btn_color_lines = QtWidgets.QPushButton(self.gbr_add_filter)
        self.btn_color_lines.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.btn_color_lines.setObjectName("btn_color_lines")
        self.lbl_filters = QtWidgets.QLabel(self.centralwidget)
        self.lbl_filters.setGeometry(QtCore.QRect(400, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_filters.setFont(font)
        self.lbl_filters.setObjectName("lbl_filters")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbr_load_image.setTitle(_translate("MainWindow", "Carga de imagen"))
        self.btn_load_image.setText(_translate("MainWindow", "Cargar imagen"))
        self.lbl_load_image.setText(_translate("MainWindow", "..."))
        self.ls_grb_lines.setTitle(_translate("MainWindow", "Selección de color lineas"))
        self.ls_btn_capture_color.setText(_translate("MainWindow", "Capturar"))
        self.ls_btn_apply_color.setText(_translate("MainWindow", "Aplicar"))
        self.ls_lbl_line_tolerance.setText(_translate("MainWindow", "11 %"))
        self.ls_btn_delete.setText(_translate("MainWindow", "Eliminar"))
        self.da_grb_draw_zones.setTitle(_translate("MainWindow", "Delimitación de areas"))
        self.da_btn_clean.setToolTip(_translate("MainWindow", "<html><head/><body><p>Limpiar</p></body></html>"))
        self.da_btn_delete.setToolTip(_translate("MainWindow", "<html><head/><body><p>Eliminar</p></body></html>"))
        self.da_cbx_executed.setText(_translate("MainWindow", "Ejecutado"))
        self.da_btn_coordinates.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar coordenadas</p></body></html>"))
        self.da_btn_lines.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.da_btn_lines.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.da_btn_eraser.setToolTip(_translate("MainWindow", "<html><head/><body><p>Borrador</p></body></html>"))
        self.da_btn_color.setToolTip(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.da_btn_color.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Dibujar linea</p></body></html>"))
        self.da_btn_view.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ver imagen</p></body></html>"))
        self.cs_grb_color_space.setTitle(_translate("MainWindow", "Cambiar espacio de color"))
        self.cs_cbx_color_space.setItemText(0, _translate("MainWindow", "COLOR_BGR2GRAY"))
        self.cs_apply.setText(_translate("MainWindow", "Aplicar"))
        self.cs_view.setText(_translate("MainWindow", "Ver"))
        self.bn_grb_binarize.setTitle(_translate("MainWindow", "Threshold"))
        self.bn_cbx_s_technique.setItemText(0, _translate("MainWindow", "THRESH_BINARY"))
        self.bn_cbx_s_technique.setItemText(1, _translate("MainWindow", "THRESH_BINARY_INV"))
        self.bn_cbx_s_technique.setItemText(2, _translate("MainWindow", "THRESH_TRUNC"))
        self.bn_cbx_s_technique.setItemText(3, _translate("MainWindow", "THRESH_TOZERO"))
        self.bn_cbx_s_technique.setItemText(4, _translate("MainWindow", "THRESH_TOZERO_INV"))
        self.bn_lbl_s_threshold_simple.setText(_translate("MainWindow", "Threshold simple"))
        self.label_2.setText(_translate("MainWindow", "Threshold adaptivo"))
        self.bn_cbx_ad_method.setItemText(0, _translate("MainWindow", "ADAPTIVE_THRESH_MEAN_C "))
        self.bn_cbx_ad_method.setItemText(1, _translate("MainWindow", "ADAPTIVE_THRESH_GAUSSIAN_C"))
        self.bn_cbx_ad_type.setItemText(0, _translate("MainWindow", "THRESH_BINARY"))
        self.bn_cbx_ad_type.setItemText(1, _translate("MainWindow", "THRESH_BINARY_INV"))
        self.bn_lbl_s_threshold_value.setText(_translate("MainWindow", "11"))
        self.bn_lbl_ad_block_size.setText(_translate("MainWindow", "Block size"))
        self.bn_lbl_ad_block_size_value.setText(_translate("MainWindow", "11 "))
        self.bn_lbl_ad_constant.setText(_translate("MainWindow", "Constant"))
        self.bn_lbl_ad_constant_value.setText(_translate("MainWindow", "11 "))
        self.bn_lbl_ad_method.setText(_translate("MainWindow", "Adaptive Method"))
        self.bn_lbl_ad_type.setText(_translate("MainWindow", "Threshold Type"))
        self.bn_btn_s_apply.setText(_translate("MainWindow", "Aplicar"))
        self.bn_btn_s_view.setText(_translate("MainWindow", "Ver"))
        self.bn_btn_add_view.setText(_translate("MainWindow", "Ver"))
        self.bn_btn_ad_apply.setText(_translate("MainWindow", "Aplicar"))
        self.gbr_add_filter.setTitle(_translate("MainWindow", "Agregar filtros"))
        self.btn_draw_zones.setText(_translate("MainWindow", "Dibujar zonas"))
        self.btn_color_lines.setText(_translate("MainWindow", "Color lineas"))
        self.lbl_filters.setText(_translate("MainWindow", "Filtros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
